name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Package name of target android app"
          default: "com.PigeonGames.Phigros"
          required: true

run-name: Deploy to ${{ inputs.package_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: prepare assets
      shell: bash
      run: |
        sudo apt-get install -y zstd

        mkdir -p staticlib
        curl -L -o staticlib/gmextra.a https://github.com/mokurin000/gm_addr_extract/releases/download/r21/libgm_addr_extract_ffi.a

    - run: |
        chmod +x ./gradlew
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h

        export GMEXTRA_PATH=$(realpath ./staticlib/gmextra.a)

        ./gradlew :module:assembleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package_name }}
        path: out/magisk_module_release/
